# -*- coding: utf-8 -*-
"""DAY - 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13B-n9Su0BlYjPt4CYlYH7cYZA4T6Il9R

variable
"""

a = 10
b = a
a = 20

print(a)
print(b)

"""all data types example

"""

a = 10
b = 3.14
c = 2+3j
d = "Hello"
e = True
f = [1, 2, 3]
g = (1, 2, 3)
h = {"name": "Sushmitha", "age": 20}
i = None


print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))

"""mutable

"""

n = [1,2,3]
n.append(4)

print(n)

"""immutable"""

x = 10
x = 20

print(x)

"""Implicit Type Casting"""

a = 9
b = 1.0

c = a + b

print(c)
print(type(c))

"""Explicit type casting

"""

a = 10
b = float(a)

print(b)
print(type(b))

"""float to Integer"""

a = 16.8
b = int(a)

print(b)
print(type(b))

"""Integer to String"""

a = 16
b = str(a)

print(b)
print(type(b))

"""String to integer"""

a = "200"

b = int(a)

print(b)
print(type(b))

"""string to Float"""

a = "300"
b = float(a)

print(b)
print(type(b))

"""f sting using in Variable"""

name = "Sushmitha"
age = 21

print(f"My name is {name} and I am {age} years old.")

"""f string using in Expressions"""

a = 10
b = 20

print(f"sum = {a + b}")

"""formatting decimal number"""

pi = 3.1415568

print(f"Value of pi = {pi:.2f}")